services:
  - type: web
    name: ghost-api
    env: dotnet
    rootDir: Ghost
    region: frankfurt
    plan: free
    buildCommand: dotnet restore && dotnet publish -c Release -o /app/publish
    startCommand: dotnet /app/publish/Ghost.dll
    envVars:
      - key: Db__Provider
        value: postgres
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: Jwt__Issuer
        value: Ghost
      - key: Jwt__Audience
        value: GhostUsers
    healthCheckPath: /api/Tasks
    autoDeploy: true
